env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
  matrix:  
    - ARCH=x86_64
      GOIMG=golang:1.6 
      DOCKER_BUILD=mastermindg/docker-flow-proxy:${VERSION}
      DOCKER_TAG=
    - ARCH=rpi
      GOIMG=kutsudock/rpi-alpine-go  
      DOCKER_BUILD=mastermindg/docker-flow-proxy:rpi-${VERSION}

sudo: required

services:
  - docker

script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -v go:/go ${GOIMG} bash -c "cd /usr/src/myapp && go get -d -v -t && go test --cover -v ./... --run UnitTest && go build -v -o docker-flow-proxy"; fi

after_success:
  - docker build -t ${DOCKER_BUILD} .
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker push ${DOCKER_BUILD} || false'

branches:
  only:
    - master

notifications:
  email: false
